### ISSUE TITLE
where to get the token

### ISSUE THREAD

**Issue by kangjinling** [parkpow/alpr-anpr-android#5]
We need to identify the Thai license plate, where can I get the token

**Comment by danleyb2** [comment]
@kangjinling Thai is only available using the on premise SDK.
1. Sign up for a free trial. https://app.platerecognizer.com/accounts/signup/
2. Install the Snapshot SDK.   https://guides.platerecognizer.com/docs/snapshot/getting-started
3. Install the android app from releases page, Update SDK url in App settings, you can leave the TOKEN blank or specify any value
4. Upload images from Android app

**Comment by kangjinling** [comment]
I want an android sdk that can recognize thai license plate offline

**Comment by danleyb2** [comment]
@kangjinling Sorry, our SDK cannot run offline on Android at the moment.
